# Generated by Django 3.0.7 on 2020-07-20 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16, unique=True)),
                ('g_position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=64, unique=True)),
                ('s_age', models.IntegerField(default=15)),
                ('s_sex', models.BooleanField(default=False)),
                ('s_height', models.FloatField(default=1.66)),
                ('s_weight', models.FloatField(default=50)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendemail.Grade')),
            ],
        ),
    ]
